# Generated by Django 4.2.2 on 2023-08-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_tax',
            field=models.IntegerField(default=0),
        ),
    ]
