# Generated by Django 4.2.2 on 2023-08-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_order_driver_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining_amount',
            field=models.FloatField(default=0),
        ),
    ]
