# Generated by Django 4.2.4 on 2023-08-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_employee_quantity_alter_order_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_id',
            field=models.IntegerField(default=5),
        ),
    ]
