# Generated by Django 4.2.4 on 2023-08-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_employee_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='final_amount_Dollar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='final_amount_LBP',
            field=models.FloatField(default=0),
        ),
    ]
