# Generated by Django 4.2.4 on 2023-08-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_remove_order_final_amount_order_final_amount_dollar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='remaining_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_amount_Dollar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_amount_LBP',
            field=models.FloatField(default=0),
        ),
    ]
