# Generated by Django 4.2.4 on 2023-08-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_remove_order_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_tax_Currency',
            field=models.CharField(default='dollar', max_length=255),
        ),
    ]
