# Generated by Django 4.2.4 on 2023-09-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_order_driver_tax_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_currency',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_Dollar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_LBP',
            field=models.FloatField(default=0),
        ),
    ]
